# Copyright Contributors to the Open Shading Language project.
# SPDX-License-Identifier: BSD-3-Clause
# https://github.com/AcademySoftwareFoundation/OpenShadingLanguage

# GitHub Actions workflow file for CI
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on:
  workflow_dispatch:

permissions: read-all

jobs:
  windows:
    name: "${{matrix.desc}} VS${{matrix.vsver}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - desc: windows-2019
            runner: windows-2019
            vsver: 2019
            generator: "Visual Studio 16 2019"
            openexr_ver: v3.2.4
            python_ver: 3.7
            simd: sse4.2
          # - desc: windows-2022
          #   runner: windows-2022
          #   vsver: 2022
          #   generator: "Visual Studio 17 2022"
          #   openexr_ver: v3.2.4
          #   python_ver: "3.9"
          #   simd: sse4.2
    runs-on: ${{ matrix.runner }}
    env:
      PYTHON_VERSION: ${{matrix.python_ver}}
      CMAKE_GENERATOR: ${{matrix.generator}}
      OPENEXR_VERSION: ${{matrix.openexr_ver}}
      USE_SIMD: ${{matrix.simd}}
      CTEST_ARGS: "--timeout 180 --repeat after-timeout:6"
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@a21f25cd3998bf370fde17e3f1b4c12c175172f9 # v2.0.0
      - name: Build setup
        shell: bash
        run: |
            ${{matrix.setenvs}}
            src/build-scripts/ci-startup.bash
      - name: Install curl
        shell: bash
        run: |
            VCPKG_INSTALLATION_ROOT=/c/vcpkg
            vcpkg install 7zip
      # choco install 7zip.install
      # - name: Install Flex and Bison
      #   shell: bash
      #   run: |
      #       git clone https://github.com/lexxmark/winflexbison
      #       cd winflexbison
      #       mkdir build
      #       cd build
      #       cmake ..
      #       cmake --build . --config release
      # - name: Install LLVM and Clang
      #   uses: KyleMayes/install-llvm-action@v2
      #   with:
      #     version: "18.1.8"
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm
      - name: Dependencies
        shell: bash
        run: |
          echo Check Ninja Version
          ninja --version
          src/build-scripts/gh-win-installdeps.bash
        # run: src/build-scripts/gh-win-installdeps.bash
      - name: New Build
        shell: bash
        run: |
          echo Check Ninja Version 2
      - name: Build
        shell: bash
        run: src/build-scripts/ci-build.bash
      - name: Testsuite
        shell: bash
        run: src/build-scripts/ci-test.bash
      - uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        if: failure()
        with:
          name: osl-${{github.job}}-VS${{matrix.vsver}}
          path: |
              build/cmake-save
              build/*.cmake
              build/CMake*
              build/testsuite/*/*.*